### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by v0dro**

### CODE REVIEW

**Comment by v0dro** [comment]
@Arafatk I'll be sending my changes to this PR. Do keep commenting on the changes if you think anything is amiss.

**Comment by arafatkatze** [comment]
Thanks a lot.
I will

**Comment by v0dro** [comment]
Tasks that I'll be finishing (in the given order):

- [ ] Integrate GR rubyplot specs into this repo.

- [ ] Integrate all the GR plot code as-is into this repo.

- [ ] Make provision for running both rmagick and GR test suites.

- [ ] Figure out a way to create a common interface for subplots that can integrate well into this repo.

**Comment by arafatkatze** [comment]
@v0dro This work is amazing.    
It works fine but I can't recommend any changes immediately, I am merging this now and we can make many changes on top of this.      
The code for scatter looks much cleaner and I will try to adopt that for other plots.      
Thanks again

**Pull request merged**
