### PR TITLE
Fixes #20

### LINKED ISSUE #20: Unclear how to set properties on each dataset individually
```
require "rubyplot"

plot = Rubyplot::Line.new
plot.title = 'Trajectory'

x = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
y1 = [0,   0.04, 0.16, 0.36, 0.64, 1.0]
y2 = [0,   0.08, 0.32, 0.72, 1.28, 2.0]

plot.data x, y1, color: :red
plot.data x, y2, color: :blue

plot.write('test.png')
```

I would expect this to allow me to set the color on each type of data. I'd also expect it to let me set things like marker size, line width, label (for the legend), etc. It looks like data only takes two arguments, though.

### PR DESCRIPTION
**Pull request by arafatkatze**

### CODE REVIEW

**Comment by arafatkatze** [comment]
@mohawkjohn @pjotrp This handles all the ideas that you have mentioned in a decent way.         
I hope this is close to your expectation of a solution      
1. >You should not be using random colors. The sequence should be predictable because users tend to create multiple plots with one line and expect the color to be uniform between them. I'd use the default sequence in Matplotlib as a first pass.             

I replaced all instances of random colors with fixed colors corresponding to different visual themes.    
[Here](https://github.com/Arafatk/magick-rubyplot/pull/21/files#diff-10c0bf3970aa5ed3b94b039d36d69807R12) It either uses the default color label corresponding to the theme or the color set by the user.             

2. > I'm confused about why you're using symbols for the label but strings for the color. I'm worried that you're still misunderstanding the purpose of symbols versus strings. (Truthfully, I can see use-cases where people would use symbols for labels, so I wouldn't disallow it, but it's an odd design choice.).              

This was certainly a bad idea from me and I never realized how odd it looked.   So I changed it and now things look like this 

 ```
 plot.data( [0, 5, 8, 15],label: :Cars, color:  :maroon)
 plot.data( [10, 3, 2, 8],label: :Bus, color:  :grey)
```         

3. > You shouldn't be using a set method. It's Ruby. You should be using def colors_array= instead.        
 
I removed this functionality all together as it seems confusing.      
If the user wants to set a particular label that can be done at the point of label addition itself.     
So if the user wants to set a particular color it can be done this way.        
  `
 plot.data( [0, 5, 8, 15],label: :Cars, color:  :maroon)`
Otherwise, the label color will default to the original one corresponding to the theme.          

4. >. Your #data method is confusing because it looks like it's changing plot, but it doesn't have a bang.          

I thought it might be confusing to have a bang with every use of data as it's blatantly obvious it's changing the object.  The [SO answer](https://stackoverflow.com/questions/612189/why-are-exclamation-marks-used-in-ruby-methods) says that sometimes it might or might not be used.      
But I will add this as it's the convention.

5. >.  I don't like that you have to provide a label for #data. You should put the most commonly used arguments first, and make label and color optional keyword arguments.         
Done

**Comment by pjotrp** [comment]
Thanks Arafat. Looks good to me. @mohawkjohn wdyt?

**Comment by translunar** [comment]
This is much better. Can you use string labels instead of symbols? (It's fine to use symbols, just wondering if strings are allowed.)

**Comment by arafatkatze** [comment]
@mohawkjohn both string labels and symbols work because it applies to_s method on symbols.           
Would you prefer only string labels work?   Or I could just replace the examples with string labels so that users generally do that?

**Comment by v0dro** [comment]
Can you shut this PR now? Or is this code still valid?

**Comment by arafatkatze** [comment]
@v0dro Well this PR is okay but a lot of changes have been made at the integration branch so mixing this work with that will require another PR.      
Besides Integration PR will solve many of the issues that John pointed out anyway so I will refer to this then.

**Pull request closed without merging**
